substitutions:
  _REGION: northamerica-northeast2
  _REPO: utsav-repo
  _SERVICE: utsav-bank-frontend
  _BACKEND_URL: ""   # set this in the trigger (your backend's Cloud Run URL)

steps:
  #Build the frontend image, baking in the backend URL
  - id: build-image
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - REACT_APP_API_URL=${_BACKEND_URL}/api/v1
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA
      - bank-frontend

  #Push the image to Artifact Registry
  - id: push-image
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA

  #Deploy the image to Cloud Run
  - id: deploy-cloudrun
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --allow-unauthenticated
      - --port=8080
      - --service-account=79505229087-compute@developer.gserviceaccount.com

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:$SHORT_SHA

options:
  logging: CLOUD_LOGGING_ONLY